Tutorty
Namanl2001/MERN-Gurujii-dev pull request #103
Opened 2021-03-25 18:12 UTC by ChitvanRamani22

## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give

2021-03-25 18:47 UTC, sagar-barapatre approved these changes

2021-03-25 22:54 UTC, Namanl2001 requested changes
LGTM with some small nits, also resolve conflicts as the form style is updated to double coloumn.

2021-03-25 22:54 UTC, Namanl2001 commented on src/components/card.jsx
> +            <br></br>
- Shift tutor below subject info.


- change line 35 to  `</br>`

2021-03-26 04:25 UTC, ChitvanRamani22 commented
@Namanl2001 i have made the required changes and pushed them .
Please do check it.

2021-03-26 21:29 UTC, Namanl2001 commented
IDK why you have force pushed but now I'm not able to pull and test your changes see [this](https://stackoverflow.com/questions/9813816/git-pull-after-forced-update). So either you can resolve this as mentioned in the above link or open a new pr or just simply attach the screenshots of the form in comments here, and please check them once by yourself so that we can merge this without any risk. You have already done some similar changes in the past so we can trust you 😄

2021-03-27 03:24 UTC, ChitvanRamani22 commented
I have attached all the screenshots.

![Screenshot (456)](https://user-images.githubusercontent.com/68965499/112708702-9abc2100-8ed9-11eb-9823-f2ab9920d2cb.png)
![Screenshot (454)](https://user-images.githubusercontent.com/68965499/112708704-9db71180-8ed9-11eb-9202-152a9ee0974f.png)
![Screenshot (453)](https://user-images.githubusercontent.com/68965499/112708770-f5ee1380-8ed9-11eb-84ec-d154f924f7ff.png)
![Screenshot (455)](https://user-images.githubusercontent.com/68965499/112708774-fa1a3100-8ed9-11eb-8c12-1287074ac913.png)

2021-03-27 06:05 UTC, ChitvanRamani22 commented
@Namanl2001 everything is working fine  and  can also be seen from the ss attached .

2021-03-27 12:02 UTC, Namanl2001 approved these changes
Great! Thanks

2021-03-27 12:03 UTC, merged