form validation
Namanl2001/MERN-Gurujii-dev pull request #169
Opened 2021-05-02 11:38 UTC by ChitvanRamani22

Closes: #107 

https://user-images.githubusercontent.com/68965499/116811800-e8771980-ab68-11eb-981f-b595611f6a8d.mp4

@Namanl2001 @sagar-barapatre please review this pr.

2021-05-04 19:04 UTC, Namanl2001 commented
Hey, we can consider this PR but this does not solve the actual issue `#107`.
The issue `107` is for example if the user clicks the submit button without filling any detail in the form or let say missing an input which is mandatory to make a post request. You can check the model in the backend directory to check which are the mandatory inputs. And then we've to show the alerts at the missed input boxes which are mandatory to be filled out.  
Do you want to add the required change in a separate PR? as this PR looks good for its purpose. Thanks

2021-05-04 19:38 UTC, Namanl2001 requested changes
Small nits otherwise LGTM

2021-05-04 19:38 UTC, Namanl2001 commented on src/components/update.jsx
> +      if (!pinRegex.test(val) || (val.length != 6 && val !== '')) {
```suggestion
      if (!pinRegex.test(val) || (val.length !== 6 && val !== '')) {
```

2021-05-04 19:38 UTC, Namanl2001 commented on src/components/update.jsx
> +      if (!phoneRegex.test(val) || (val.length != 10 && val !== '')) {
```suggestion
      if (!phoneRegex.test(val) || (val.length !== 10 && val !== '')) {
```

2021-05-04 19:38 UTC, Namanl2001 commented on src/components/form.jsx
> +      if (!pinRegex.test(val) || (val.length != 6 && val !== '')) {
```suggestion
      if (!pinRegex.test(val) || (val.length !== 6 && val !== '')) {
```

2021-05-04 19:38 UTC, Namanl2001 commented on src/components/form.jsx
> +      if (!phoneRegex.test(val) || (val.length != 10 && val !== '')) {
```suggestion
      if (!phoneRegex.test(val) || (val.length !== 10 && val !== '')) {
```

2021-05-05 05:31 UTC, ChitvanRamani22 commented
> Hey, we can consider this PR but this does not solve the actual issue `#107`.
> The issue `107` is for example if the user clicks the submit button without filling any detail in the form or let say missing an input which is mandatory to make a post request. You can check the model in the backend directory to check which are the mandatory inputs. And then we've to show the alerts at the missed input boxes which are mandatory to be filled out.  
> Do you want to add the required change in a separate PR? as this PR looks good for its purpose. Thanks

@Namanl2001 i will create a seperate pr for that issue but for this pr should i create a seperate issue and attach this pr as a reference or you will directly merge it?

2021-05-05 13:23 UTC, Namanl2001 approved these changes
Thanks for the PR.

2021-05-05 13:24 UTC, Namanl2001 commented
>  will it get merged without any issue?

We already have an issue for that `#107`

2021-05-05 13:24 UTC, merged

2021-05-05 14:06 UTC, ChitvanRamani22 commented
> Thanks for the PR.

My pleasure!