Improved Form Responsiveness
Namanl2001/MERN-Gurujii-dev pull request #175
Opened 2021-05-05 10:54 UTC by theBeginner86

## Related Issue 

- In this PR, I have solved the responsiveness of the form of our website. I have used standard breakpoints with media query to solve this issue. 

Closes: #173 

### Describe the changes you've made

I have made changes in the following files:
- styles.css
Here, I have used media query and added following breakpoints: <=767px(for mobile devices), >=768px & <=1199px(for tablet and medium sized displays), and >=1200px(for desktops and larger screen devices).
Then, I have just added few paddings, set the widths and corrected the margins.
- form.jsx
There I changed the class from col-sm-2 to col-sm-3 for two proper alignment of the input boxes.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code: NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

## Additional Info (optional)
Any additional information you want to give:

- For smaller display mobile devices:
<img width="538" alt="Screenshot 2021-05-05 at 4 09 00 PM" src="https://user-images.githubusercontent.com/73700530/117130384-9ed33c80-adbd-11eb-82e7-9200b34e46ef.png">

- For medium to high display mobile devices:
<img width="764" alt="Screenshot 2021-05-05 at 4 08 30 PM" src="https://user-images.githubusercontent.com/73700530/117130530-d0e49e80-adbd-11eb-928b-9c4682f779f3.png">

- For tablets and medium display computers:
<img width="1150" alt="Screenshot 2021-05-05 at 4 08 07 PM" src="https://user-images.githubusercontent.com/73700530/117130601-eb1e7c80-adbd-11eb-9701-3118de40c7a0.png">

-For desktops and larger devices:
<img width="1440" alt="Screenshot 2021-05-05 at 4 07 51 PM" src="https://user-images.githubusercontent.com/73700530/117130655-fec9e300-adbd-11eb-95bf-da13aa5c8772.png">

2021-05-05 13:20 UTC, Namanl2001 commented on src/components/style.css
> +    font-size: 0.6rem;
0.6 is too small. Make it 0.8

2021-05-05 13:21 UTC, Namanl2001 requested changes
![image](https://user-images.githubusercontent.com/56021229/117147345-cbde1a00-add2-11eb-96e8-fe6a325fc03e.png)


As you can see the right part of the form is out of screen. please fix it. Other things looks good.

2021-05-05 13:21 UTC, Namanl2001 commented on src/components/style.css
> +    font-size: 0.7rem;
```suggestion
    font-size: 0.9rem;
```

2021-05-05 13:42 UTC, theBeginner86 commented on src/components/style.css
> +    font-size: 0.6rem;
ok I will do it.

2021-05-05 13:42 UTC, theBeginner86 commented on src/components/style.css
> +    font-size: 0.7rem;
ok I will do it.

2021-05-05 14:39 UTC, theBeginner86 commented
@Namanl2001 
I have made the requested changes, Please review it.

2021-05-05 16:25 UTC, Namanl2001 commented
Can you please add a screen shot for 360 X 640 resolution?

2021-05-05 17:05 UTC, theBeginner86 commented
<img width="708" alt="Screenshot 2021-05-05 at 10 34 30 PM" src="https://user-images.githubusercontent.com/73700530/117180760-276bd000-adf2-11eb-954e-685a183e257d.png">

2021-05-06 19:12 UTC, Namanl2001 requested changes
I just played a lil bit with the css. IMO we should add one more configuration as follows:
```
@media screen and (min-width: 500px) and (max-width: 767px) {
  div.formRoot,
  select.custom-select,
  input.form-control {
    font-size: 0.8rem;
  }
  select.custom-select,
  input.form-control {
    width: 100%;
  }
  div.form-child-left,
  div.form-child-right {
    flex: 100%;
  }
  div.modal-content {
    margin: 100px auto;
    width: 450px;
    position: relative;
  }
}
```

Feel free to make more changes according to your viewing experience we just need to make the form proper and readable

2021-05-06 19:12 UTC, Namanl2001 commented on src/components/style.css
> +    margin: 300px auto;
```suggestion
    margin: 100px auto;
```

2021-05-06 19:12 UTC, Namanl2001 commented on src/components/style.css
> +@media screen and (max-width: 767px) {
```suggestion
@media screen and (max-width: 500px) {
```

2021-05-07 08:36 UTC, theBeginner86 commented
I made the requested changes, and also added a separate media query to handle uncertainty in the responsiveness. Let me know how it looks now.

2021-05-08 11:07 UTC, Namanl2001 commented on src/components/style.css
> +    margin-top: 100px;
```suggestion
    margin-top: 300px;
```

The heading is missing in this range. Please make the suggested change.

2021-05-08 11:33 UTC, Namanl2001 approved these changes
LGTM! Thanks for the super quick changes. Thanks
Feel free to pick more issues.

2021-05-08 11:35 UTC, theBeginner86 commented
> LGTM! Thanks for the super quick changes.
> Feel free to pick more issues.

I am happy to help. 😁

2021-05-08 11:43 UTC, merged