alert validation
Namanl2001/MERN-Gurujii-dev pull request #178
Opened 2021-05-05 20:20 UTC by ChitvanRamani22

Closes: #107 
@Namanl2001 if any of the required field (as per the schema) is empty an alert will pop up and the form wont be submitted.

2021-05-06 19:18 UTC, Namanl2001 commented
Hey @ChitvanRamani22 your changes look nice but we are trying to achieve something like [this](https://user-images.githubusercontent.com/41958505/112602110-482b2800-8e39-11eb-8d9b-47068e1c6d44.png). As it looks nicer and user friendly. WDYT? In alert we are not aware of which input field we are missing.

2021-05-07 03:58 UTC, ChitvanRamani22 commented
@Namanl2001 this is what i have already done in my previous pr and there you commemted that in issue 107 we need a alert of any of the required field as per the model is missing.
So thats what i did.

2021-05-07 04:05 UTC, ChitvanRamani22 commented
I can do one thing that is  print the messeges of requirement of that particular input below that input field.
Will that be fine @Namanl2001

2021-05-07 12:40 UTC, ChitvanRamani22 commented
@Namanl2001 please have a look at this commit and let me know if this correct.

2021-05-08 12:02 UTC, Namanl2001 commented
We can consider this but it does not have good UI/UX and looks lil clumsy at first. WDYT?
Have you tried to implement this? https://user-images.githubusercontent.com/41958505/112602110-482b2800-8e39-11eb-8d9b-47068e1c6d44.png

2021-05-08 12:21 UTC, ChitvanRamani22 commented
@Namanl2001 the image shows the same thing that at starting till the fields are empty the messege will be displayed else it will disappear.

2021-05-08 12:25 UTC, Namanl2001 commented
> @Namanl2001 the image shows the same thing that at starting till the fields are empty the messege will be displayed else it will disappear.

Nope, it's not like that. The warnings are only shown when a user clicks the submit form button, else there is no err/warning.

2021-05-14 20:13 UTC, Namanl2001 commented
Did you find any solution for this?

2021-05-15 04:55 UTC, ChitvanRamani22 commented
@Namanl2001 not yet.

2021-05-23 18:01 UTC, ChitvanRamani22 commented
![IMG-20210523-WA0020.jpeg](https://user-images.githubusercontent.com/68965499/119271416-0511e900-bc1f-11eb-8e01-8b30ab760d8c.jpeg)
@Namanl2001 please review now.

2021-05-23 18:47 UTC, Namanl2001 commented
Looks more good now 👍 Few things

- can we have toast msg instead of windows.alert() ?
- make `name` compulsory
- Styling  of the form is being altered

2021-05-23 18:52 UTC, ChitvanRamani22 commented
@Namanl2001 name is compulsory.
But as the name input field is not empty the astrik sign is not visible

2021-05-23 19:02 UTC, ChitvanRamani22 commented
@Namanl2001 toast messege is not working as should.

2021-05-24 06:55 UTC, ChitvanRamani22 commented
@Namanl2001 i have added toast messege instead of alert.

2021-05-24 12:14 UTC, Namanl2001 commented
> @Namanl2001 i have added toast messege instead of alert.

will this err be shown on the form header? Please attach screenshot

2021-05-28 19:55 UTC, Namanl2001 requested changes
make [this](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/40a022c0c87d19118b600d13211512d94c57c3b0/src/components/style.css#L469) `margin-right`.

Also make [this](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/40a022c0c87d19118b600d13211512d94c57c3b0/src/components/update.jsx#L237) `col='sm-2'` -> `col='sm-3'` for all the four classes in update.jsx

The above nits are for the styling part else LGTM. But the main thing of concern here is after these changes I'm not able to update the user profile, looks like a bug. Please look into it.

Thanks

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/form.jsx
> +        errors.title = val == '' ? '*' : '';
```suggestion
        errors.title = val === '' ? '*' : '';
```

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/form.jsx
> +        errors.subject = val == '' ? '*' : '';
duplicate

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/form.jsx
> +        errors.tutor = val == '' ? '*' : '';
duplicate

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/update.jsx
> +        errors.title = val == '' ? '*' : '';
duplicate

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/update.jsx
> +        errors.subject = val == '' ? '*' : '';
duplicate

2021-05-28 19:55 UTC, Namanl2001 commented on src/components/update.jsx
> +        errors.tutor = val == '' ? '*' : '';
duplicate

2021-05-30 08:43 UTC, ChitvanRamani22 commented
> make [this](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/40a022c0c87d19118b600d13211512d94c57c3b0/src/components/style.css#L469) `margin-right`.
> 
> Also make [this](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/40a022c0c87d19118b600d13211512d94c57c3b0/src/components/update.jsx#L237) `col='sm-2'` -> `col='sm-3'` for all the four classes in update.jsx
> 
> The above nits are for the styling part else LGTM. But the main thing of concern here is after these changes I'm not able to update the user profile, looks like a bug. Please look into it.
> 
> Thanks

@Namanl2001 can you please tell in which line number i want to change it to margin-right.

2021-05-30 08:46 UTC, Namanl2001 commented
Click on attached hyperlinks in the above comment.

2021-05-30 10:53 UTC, ChitvanRamani22 commented
@Namanl2001 now everything is working fine!😀

2021-05-30 14:47 UTC, Namanl2001 commented
Please resolve the conflicts then I will merge this tomorrow. Thanks

2021-05-31 14:22 UTC, ChitvanRamani22 commented
@Namanl2001 can you please merge this now.

2021-05-31 17:30 UTC, Namanl2001 commented
check is not passing yet. Please look into it

2021-05-31 17:46 UTC, ChitvanRamani22 commented
@Namanl2001 i dont know why that chck is not passing i havent made any change in user.controller file.

2021-05-31 18:06 UTC, Namanl2001 commented
PHAL @ [this](https://github.com/Namanl2001/MERN-Gurujii-dev/pull/18#issuecomment-824134125)

2021-06-01 11:31 UTC, Namanl2001 reviewed
Let's do this. And check

2021-06-01 15:08 UTC, Namanl2001 requested changes
Small nit.
Also please comment [this line](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/2521487e367afbda9421fa91cdf127973931f53c/backend/controllers/user.controller.js#L99) for now.

also after doing these changes please heck once if all the functions ae working properly ene to end and as expected.
Thanks

2021-06-01 15:10 UTC, Namanl2001 requested changes
Small nit.
Also please comment [this line](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/2521487e367afbda9421fa91cdf127973931f53c/backend/controllers/user.controller.js#L99) for now.

also after doing these changes please heck once if all the functions ae working properly ene to end and as expected.
Thanks

2021-06-01 15:10 UTC, Namanl2001 commented on src/components/form.jsx
> +              alert(
```suggestion
             ! alert(
```

2021-06-01 15:44 UTC, ChitvanRamani22 commented
@Namanl2001 i have done the changes.
And everything is working fine now.

2021-06-01 18:31 UTC, Namanl2001 approved these changes
Thanks @ChitvanRamani22 for your patience and great work. 🚀

2021-06-01 18:32 UTC, merged