implement teachers popularity
Namanl2001/MERN-Gurujii-dev pull request #222
Opened 2021-05-29 13:03 UTC by subhangi2731

## Related Issue 

- implement teachers popularity among users

Closes: #181

### Describe the changes you've made

Made changes in usercontroller.js , usermodel.js and card.js

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement in the existing features
- [ ] Other

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have verified/tested my code by running it locally.

2021-05-29 13:03 UTC, subhangi2731 commented
@Namanl2001 please merge my pr I have done this

2021-05-29 18:23 UTC, subhangi2731 commented
@Namanl2001 please check and let me know and merge this pr it took a lot to me to do evrything

2021-05-30 05:11 UTC, subhangi2731 commented
@Namanl2001 i request u please check and merge my pr

2021-05-30 08:31 UTC, Namanl2001 requested changes
Small nits. Thanks for your patience

2021-05-30 08:31 UTC, Namanl2001 commented on src/components/card.jsx
> +      });
please handle `res` and `err` properly. And remove the console logs

Phal @ [this](https://itnext.io/javascript-error-handling-from-express-js-to-react-810deb5e5e28)

2021-05-30 08:31 UTC, Namanl2001 commented on src/components/card.jsx
> +          <div className='flip-box' onClick={this.state.clicked?'':this.handleClick}>
There is a hover effect on cards so this onclick will not work practically.
I'll suggest you to move this `onClick` event listener to the `click here to read more` button on the cards back.

2021-05-31 16:42 UTC, tend2infinity commented
I am taking over this PR since @subhangi2731 isn't active

2021-06-03 18:17 UTC, subhangi2731 commented
@tend2infinity why dont u create ur own pr why are u behind my pr I had health issues thatwhy I couldnt reply that doesnt mean I am not active and then u take over my pr @Namanl2001 as this is my pr and I have worked on this can I make changes and can u merge because I had send the pr before may 31 so I should get scores for this

2021-06-03 18:46 UTC, Namanl2001 commented
Yes, @subhangi2731 you can still make the required changes and we can have this merge.

2021-06-04 11:28 UTC, Namanl2001 commented
@subhangi2731 FYI your changes after tonight (i.e. 4/6/21 23:59 P.M. IST) will not be accepted. Hurry up!
Thanks

2021-06-05 16:20 UTC, closed without merging