Card-Animation
Namanl2001/MERN-Gurujii-dev pull request #28
Opened 2021-03-09 17:21 UTC by ChitvanRamani22

2021-03-09 17:32 UTC, Namanl2001 commented
15k lines of change? Have you not followed instructions to setup the project? We use yarn to install the dependencies but it seem like that you have used npm install instead of yarn install.
To correct this, delete package-lock.json in the backend folder, run yarn install in the same folder, commit your changes and push them again in this branch only.

2021-03-09 19:19 UTC, Namanl2001 requested changes
Good work! Some changes are needed.

2021-03-09 19:19 UTC, Namanl2001 commented on src/App.css
> +  box-shadow: 4px 4px #D3D3D3;
transform: scale(1.1);
box-shadow: 6px 6px #D3D3D3;

2021-03-09 19:19 UTC, Namanl2001 commented on package.json
> +    "concurrently": "^6.0.0",
Remove this, and run `yarn install` from the root of this repo.

2021-03-09 19:19 UTC, Namanl2001 commented on backend/server.js
> +const { username, pass,myCluster  } = config;
Not needed. uncomment line no. 6 and remove line no. 7 & 8

2021-03-09 19:19 UTC, Namanl2001 commented on backend/routes/users.js
> +const {pass}=config;
`const { pass } = require('../config'); ` should work.

2021-03-10 08:07 UTC, Namanl2001 requested changes
small nit

2021-03-10 08:07 UTC, Namanl2001 commented on backend/routes/users.js
> -
seems like a non intentional change.

2021-03-10 08:35 UTC, Namanl2001 approved these changes
LGTM! Thanks.

2021-03-10 08:37 UTC, merged

2021-03-10 08:39 UTC, ChitvanRamani22 commented
Thanks a lot sir.
Do add this to my gssoc contribution.

On Wed, 10 Mar 2021, 2:05 pm Naman Lakhwani, ***@***.***>
wrote:

> *@Namanl2001* approved this pull request.
>
> LGTM! Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Namanl2001/MERN-Gurujii-dev/pull/28#pullrequestreview-608448947>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQOFI6ZJOXCBLMNAFUVKJ4DTC4VNRANCNFSM4Y4CGU7A>
> .
>

2021-03-10 09:50 UTC, ChitvanRamani22 commented
Sir just to clarify that i am a girl.
Thanks

On Wed, 10 Mar 2021, 2:09 pm Chitvan Ramani, ***@***.***>
wrote:

> Thanks a lot sir.
> Do add this to my gssoc contribution.
>
> On Wed, 10 Mar 2021, 2:05 pm Naman Lakhwani, ***@***.***>
> wrote:
>
>> *@Namanl2001* approved this pull request.
>>
>> LGTM! Thanks.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Namanl2001/MERN-Gurujii-dev/pull/28#pullrequestreview-608448947>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQOFI6ZJOXCBLMNAFUVKJ4DTC4VNRANCNFSM4Y4CGU7A>
>> .
>>
>